[project]
name = "warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "networkx[default]>=3.6.1",
    "ortools>=9.15.6755",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "uvicorn>=0.53.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
filterwarnings = [
    "ignore::DeprecationWarning",
]
